[package]
name = "database"
version = "0.1.0"
edition = "2021"

[dependencies]
pgvector = { version = "0.3", features = ["sqlx"] }
sqlx = { version = "0.7", features = ["postgres", "time"] }
time = "0.3"
tracing = "0.1"
